version: '3.7'

services:
  # PostgreSQL service
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres #Change to data from env file
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
    - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: darya4shauch@gmail.com
      PGADMIN_DEFAULT_PASSWORD: postgresmaster
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
     - postgres
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1s
      timeout: 2s
      retries: 10
volumes:
  pgdata:
  pgadmin-data:
  redis:
  


 

